name: "Bundlewatch Github Action - on Tracked Branches Push"

on:
  push: 
    branches:
    - master

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}